### ISSUE TITLE
Clash between Ipopt.jl and MadNLP.jl issued by MUMPS_seq_jll

### ISSUE THREAD

**Issue by frapac** [sshin23/MadNLP.jl#13]
In our team, we ran into the following issue when installing MadNLP.jl and Ipopt.jl in the same Julia session: 
```
session> test MadNLP 
...
free(): invalid pointer

signal (6): Aborted
in expression starting at /home/fpacaud/exa/MadNLP.jl/test/MOI_interface_test.jl:12
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fe0b3a01906)
unknown function (ip: 0x7fe0b3a08979)
cfree at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
dmumps_end_driver_ at /home/fpacaud/.julia/artifacts/9d7c145c183adb9f2f4df30a7531e4ef1c95cdc3/lib/libdmumps.so (unknown line)
dmumps_ at /home/fpacaud/.julia/artifacts/9d7c145c183adb9f2f4df30a7531e4ef1c95cdc3/lib/libdmumps.so (unknown line)
dmumps_f77_ at /home/fpacaud/.julia/artifacts/9d7c145c183adb9f2f4df30a7531e4ef1c95cdc3/lib/libdmumps.so (unknown line)
dmumps_c at /home/fpacaud/.julia/artifacts/9d7c145c183adb9f2f4df30a7531e4ef1c95cdc3/lib/libdmumps.so (unknown line)
```

As detailed in the stacktrace, the issue is caused by MUMPS. Investigating it further: 
- MadNLP is working fine with `MUMPS_seq_jll` 5.3.5 
- The crash could be reproduced if we install MadNLP alone and fix explicitly the version of `MUMPS_seq_jll` to 5.2.1
- the problem is that [Ipopt.jl requires explicitly](https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/blob/main/Project.toml#L18) `MUMPS_seq_jll` 5.2.1: see the related discussion here https://github.com/jump-dev/Ipopt.jl/issues/242

I see three solutions onward: 
- we fix explicitly the version of `MUMPS_seq_jll` to 5.3.5 in MadNLP's Project.toml (in that case, we could not use anymore Ipopt and MadNLP together) 
- we fix the error we are observing with `MUMPS_seq_jll` 5.2.1 (but that would be hard, I think)
- we wait till Ipopt.jl supports `MUMPS_seq_jll` 3.5.1: https://github.com/jump-dev/Ipopt.jl/issues/246

**Comment by sshin23** [comment]
Thanks @frapac!
This issue is fixed in PR #14. Now MadNLP checks the version of `MUMPS_seq_jll` and makes a necessary change, so it should work either with `MUMPS_seq_jll 5.2.1` or `MUMPS_seq_jll 5.3.5`. Could you check if `MadNLP#master` works properly within ExaPF?

**Comment by frapac** [comment]
Thanks to you @sshin23 , that was a quick fix! This is the best situation for us, as it would allow to use Ipopt.jl in the same environment as MadNLP.jl.
I just checked on `MadNLP#master`, and I confirm that #14 fixes the issue we were facing. I am closing this issue.

**Comment by odow** [comment]
Ipopt is unlikely to support MUMPS without someone motivated enough to go digging.
