### ISSUE TITLE
[CUDA] Add support for cuSOLVER's sytrs 

### ISSUE THREAD

**Issue by frapac** [sshin23/MadNLP.jl#35]
At the moment, when using Bunch-Kaufman with `LapackGPU`, MadNLP is using cusolver to compute the factorization on the GPU, then copy the factorization back to the CPU to do the triangular solver with OpenBlas. 

The reason of this additional data transfer is that the routine `sytrs` is not implemented properly in cusolver (there exists a function `cusolverDnDsytrs` in the API, but apparently it doesn't do anything, and this function was not even referenced in the cusolver's documentation).

However, it looks like they have included a new `sytrs` function in CUDA 11.3.1: cf the [documentation](https://docs.nvidia.com/cuda/cusolver/index.html#cusolverDnXsytrs) (strangely, they don't mention this new function in the release note).
It would be interesting to test this new function inside MadNLP (it would require to wrap the new `cusolverDnXsytrs` inside `CUDA.jl`). If it works, we would save one expensive data transfer :-)

**Comment by sshin23** [comment]
I just tested the new `cusolverDnXsytrs` in CUDA 11.3.1 and it works! Check [this commit](https://github.com/sshin23/MadNLP.jl/commit/fcc9b97e33326bd730487218e2e6c8eb2e92f74d) in the ss/cuda_sytrs branch. It should work with `CUDA#master` and `GPUCompiler#master`. 

In this commit, I'm directly ccall-ing the cusolverDnXsytrs, as CUDA.jl doesn't have a wrapper for this function yet. A bit weird thing is that cusolverDnXsytrs doesn't work with Cint but works with Int64. So I needed to create another ipiv array for an Int64 array.

I'll work on a PR for this change once the current CUDA#master is released in their next version.

**Comment by sshin23** [comment]
And in order to check the inertia without moving the LDLT factorization result to CPU, `inertia(M::LapackGPU.Solver)` needs to be implemented. [This part](https://github.com/sshin23/MadNLP.jl/blob/2ce1a302b38345beccd6905051659721c9063a4c/src/LinearSolvers/lapackcpu.jl#L168-L189) should be modified.

**Comment by frapac** [comment]
That's good to hear, I am looking forward to test that! 
About the inertia, do you know by any chance if we could use MadNLP in inertia-free mode with LapackGPU? And if so, how would it impact the performance?

**Comment by sshin23** [comment]
@frapac for most cases the inertia-free mode should work fine, and the performance is similar to that of the inertia-based mode. But I do not have an extensive benchmark result yet.

**Comment by frapac** [comment]
I would be interested to discuss that more thoroughly :-) 

Anyway, I will think of a way to compute the inertia on the GPU. Maybe the fastest way would consist in just moving back the diagonal of the factorization to the host and compute the inertia directly on it...

**Comment by sshin23** [comment]
yes, indeed. Not sure what would be the best way because of my limited understanding of GPU programming 😁 Let me know if you come up with an idea of how to compute inertia
